### ISSUE TITLE
rvcc 仓库 CMakeLists.txt 可改进的地方

### ISSUE THREAD

**Issue by daquexian** [sunshaoce/rvcc-course#1]
1. `project(rvcc)` 没有写 language，默认的 language 是 `C CXX`（见 [文档](https://cmake.org/cmake/help/latest/command/project.html) 的 `LANGUAGES` 一节），而这个项目应该只会用到 c 语言，所以可以改为 `project(rvcc C)`
2. `SET( CMAKE_C_FLAGS "-std=c11 -g -fno-common" )` 有两处可以改进的地方，一个是 set 可以改为小写，和其它地方（`project`、`add_executable` 等）大小写统一，一个是可以重写为 target-based 的 modern cmake 风格：`target_compile_options(rvcc PRIVATE -std=c11 -g -fno-common)`，如果后期 target 变多，逐个 target 设置不方便，可以改为使用 `add_compile_options` 设置全局的 flags，也比直接设置 CMAKE_C_FLAGS 要更现代一些

**Comment by sunshaoce** [comment]
好的，感谢！会逐步吸收您的意见，SET问题，会直接rebase进行修改。

**Comment by sunshaoce** [comment]
已经全部吸纳，非常感谢！
