### ISSUE TITLE
注释顺序错误

### ISSUE THREAD

**Issue by jiangshengdev** [sunshaoce/rvcc-course#12]
https://github.com/sunshaoce/rvcc/blob/37f8a4fc34f8b3a805bb927dfb20feb8d3b8530d/codegen.c#L73

// neg a0, a0是 sub a0, x0的别名, a0，即a0=0-a0
应该为
// neg a0, a0是 sub a0, x0, a0的别名，即a0=0-a0

**Comment by sunshaoce** [comment]
好的，非常感谢！

**Comment by sunshaoce** [comment]
已纠正。
